test
Signed-off-by: Joshua Sickmeyer <joshua.sickmeyer@linaro.org>

diff --git a/.github/workflows/github-actions-pr.yml b/.github/workflows/github-actions-pr.yml
--- a/.github/workflows/github-actions-pr.yml
+++ b/.github/workflows/github-actions-pr.yml
@@ -6,7 +6,9 @@ on:
 jobs:
   PR-Action:
     runs-on: ubuntu-latest
+    
     steps:
+      - run: echo "failed=0" >> $GITHUB_ENV
       - uses: actions/checkout@v2
       - uses: actions/setup-node@v2
         with:
@@ -16,12 +18,17 @@ jobs:
           repo-token: ${{ secrets.TEST_TOKEN }}
           message: |
             PR Action in progress
-      - run: npm install
-      - run: npm test
-        if: ${{ failure() }}
-      - uses: mshick/add-pr-comment@v1
+          allow-repeats: true
+      - name: install-node-modules
+        run: npm install
+      
+      - name: mocha-npm-test
+        run: npm test
+        if: ${{ failure() }} | echo "failed=1" >> $GITHUB_ENV
+        uses: mshick/add-pr-comment@v1
         with:
           repo-token: ${{ secrets.TEST_TOKEN }}
           message: |
             Testing failed.
-      - run: exit 1
+          allow-repeats: true
+      - run: echo "exit ${{ env.failed }}"
